spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
#mvc:
#  view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp         

# local 환경
---
debug : true
spring.profiles: local
#  datasource:
#    data: classpath:data-h2.sql # 시작할때 실행시킬 script
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
spring.profiles.include: real-db  
spring.devtools.livereload.enabled: true

server:
  port: 8081    

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082